### ISSUE TITLE
1.61版本换成v1.07重复下载文件bug一样

### ISSUE THREAD

**Issue by halointernet** [leiurayer/downkyi#1046]
https://github.com/yaobiao131/downkyicore/releases/tag/v1.0.7 版本暂时替代1.61bug重复下载一个PV视频的bug一致
文件log:
`2024/2/20 0:33:52   [1]   ERROR   SettingsManager  Could not find file 'D:\DownKyi-1.0.7-1.win-x64\Config\Settings'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at DownKyi.Core.Settings.SettingsManager.GetSettings()
`

**Comment by yaobiao131** [comment]
具体是什么现象
