### ISSUE TITLE
下载大量视频后程序无法打开

### ISSUE THREAD

**Issue by wtywtykk** [leiurayer/downkyi#250]
出现启动界面后就崩溃，log文件夹无log产生
中间还出现了些其他的问题，表现为aria2的session出现一些相同任务，下载的时候有时候提示任务出错但是进度条依旧在跑，或者进度条没在跑但是有网络流量。一般等多出来的任务自行结束之后才能正常。然后我会定期重启一下，但是这次关掉之后就打不开了

**Comment by wtywtykk** [comment]
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) in f:\dd\ndp\clr\src\BCL\system\throwhelper.cs:line 72
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) in f:\dd\ndp\clr\src\BCL\system\collections\generic\dictionary.cs:line 393
   at System.Collections.Generic.Dictionary`2.OnDeserialization(Object sender) in f:\dd\ndp\clr\src\BCL\system\collections\generic\dictionary.cs:line 428
   at System.Runtime.Serialization.ObjectManager.RaiseDeserializationEvent() in f:\dd\ndp\clr\src\BCL\system\runtime\serialization\objectmanager.cs:line 1112
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage) in f:\dd\ndp\clr\src\BCL\system\runtime\serialization\formatters\binary\binaryobjectreader.cs:line 204
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage) in f:\dd\ndp\clr\src\BCL\system\runtime\serialization\formatters\binary\binaryformatter.cs:line 199
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream) in f:\dd\ndp\clr\src\BCL\system\runtime\serialization\formatters\binary\binaryformatter.cs:line 113
   at DownKyi.Core.Storage.Database.Download.DownloadDb.<>c__DisplayClass9_0.<Query>b__0(SQLiteDataReader reader) in C:\Users\163wt\Desktop\downkyi\src\DownKyi.Core\Storage\Database\Download\DownloadDb.cs:line 174
   at DownKyi.Core.Storage.Database.DbHelper.ExecuteQuery(String sql, Action`1 action) in C:\Users\163wt\Desktop\downkyi\src\DownKyi.Core\Storage\Database\DbHelper.cs:line 100
   at DownKyi.Core.Storage.Database.Download.DownloadDb.Query(String sql) in C:\Users\163wt\Desktop\downkyi\src\DownKyi.Core\Storage\Database\Download\DownloadDb.cs:line 163
   at DownKyi.Core.Storage.Database.Download.DownloadDb.QueryAll() in C:\Users\163wt\Desktop\downkyi\src\DownKyi.Core\Storage\Database\Download\DownloadDb.cs:line 130
   at DownKyi.Services.Download.DownloadStorageService.GetDownloading() in C:\Users\163wt\Desktop\downkyi\src\DownKyi\Services\Download\DownloadStorageService.cs:line 54
   at DownKyi.App.CreateShell() in C:\Users\163wt\Desktop\downkyi\src\DownKyi\App.xaml.cs:line 58
   at Prism.PrismApplicationBase.Initialize() in /_/src/Wpf/Prism.Wpf/PrismApplicationBase.cs:line 76
   at Prism.PrismApplicationBase.InitializeInternal() in /_/src/Wpf/Prism.Wpf/PrismApplicationBase.cs:line 42
   at Prism.PrismApplicationBase.OnStartup(StartupEventArgs e) in /_/src/Wpf/Prism.Wpf/PrismApplicationBase.cs:line 33
   at DownKyi.App.OnStartup(StartupEventArgs e) in C:\Users\163wt\Desktop\downkyi\src\DownKyi\App.xaml.cs:line 144
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 980
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 927
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 916
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at DownKyi.App.Main()

反序列化时dictionary里面出现了重复key，是不是多线程没加锁导致的？

**Comment by snowrabbit-top** [comment]
这个解决了吗,我也是打不开了,突发奇想多线程来回切结果崩了

**Comment by leiurayer** [comment]
目前我的环境无法复现这个问题，我暂时先捕获数据库可能的异常，输出log，再来查找问题

**Comment by wtywtykk** [comment]
[Download_debug_bk.zip](https://github.com/leiurayer/downkyi/files/8234216/Download_debug_bk.zip)
这是我出问题的数据库，其中45	9af2d4e6fc4c4c76950dd31cf9d46d70这一项有问题。
我是手动修复的序列化数据，单纯捕获异常的话感觉会丢失任务。

**Comment by leiurayer** [comment]
[v1.5.x](https://github.com/leiurayer/downkyi/tree/v1.5.x) 修复了这个问题， @wtywtykk
